### ISSUE TITLE
what is the main difference

### ISSUE THREAD

**Issue by vxpert** [Esri/map-tools-template#5]
Thanks for doing this.... I had recently started with dojo... Got boilerplate way .. as this sample is based on boilerplate as base....but what is main difference between this sample and classic viewer

https://github.com/Esri/basic-viewer-template

implementing the same thing with different techniques.... or any difference if so then what is better technique..

Regards
Nauman

**Comment by kellyhutchins** [comment]
Nauman
The Map Tools is a better option to use because it uses the AMD style code. Map Tools is an updated to the Classic Viewer which we have retired and don't plan on updating in the future. The Map Tools template is where we'll focus our development efforts.

**Comment by vxpert** [comment]
Thanks kellyhutchins for quick response.. firstly i searched google and came to classic viewer .. spent two days but not got .. then came to biolerpalte and get easily but was unable to transform classic viewer in that style.. so came to this via arcgis webmap creation.... 

Why not you people give its link on classic viewer page on github
Easily getting this one how it is doing.....One thing more related to this i am trying to change my own services rather than farm field services that's data coming in table but unable to get where those service links are intialized or have to be replaced.

Regards

**Comment by kellyhutchins** [comment]
@vxpert Good suggestion  I updated the classic viewer page to have a note that directs people to this repo.  The templates were all designed to work with web maps instead of defining maps using individual map services. However others have gotten this to work by defining a local web map. Instructions for how they accomplish this can be found here: 

https://github.com/Esri/Viewer/wiki/local-definition
